[build]
  publish = "frontend/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

# Specify functions requirements separately
[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-basic"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
